# syntax=docker/dockerfile:1
# build environment
FROM node:20-alpine AS build

# set working directory in image
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH for hot reloading
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies (node_modules) 
# npm ci will remove any previous existing node modules
COPY package*.json ./
RUN npm install
RUN npm install react-scripts -g

# add app
COPY . ./

# run npm start from package json
CMD ["npm","run","dev"] 
