# syntax=docker/dockerfile:1
# build environment
FROM node:20-alpine AS build

# set working directory in image
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH for hot reloading
ENV PATH /app/node_modules/.bin:$PATH

ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL

# update npm to latest
RUN npm install npm@latest -g

# install app dependencies (node_modules) 
COPY package*.json ./
RUN npm install
RUN npm install react-scripts -g

# add app
COPY . ./

EXPOSE $PORT

# run npm start from package json
CMD ["npm","run","start", "--","--port","3001"] 
