version: "3"

services:
  dev-backend:
    image: dev-ah-annotations-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    stop_signal: SIGINT
    ports:
      - 3000:3000
    expose:
      - 3000
    env_file:
      - ./backend/.env.development
  dev-frontend:
    image: dev-ah-annotations-frontend:latest
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    stop_signal: SIGINT
    ports:
      - 3001:3001
    expose:
      - 3001
    volumes:
      - /app/node_modules
      - ./frontend:/app
    env_file:
      - ./frontend/.env.development
