version: '3'

services:
  prod-backend:
    image: prod-ah-annotations-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    stop_signal: SIGINT
    ports:
      - 3000:3000
  dev-frontend:
    image: dev-ah-annotations-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    stop_signal: SIGINT
    ports:
      - 3001:3001
    volumes:
      - ".:/app"
      - "/app/node_modules"
    env_file:
      - ./frontend/.env
